version: '3.8'

services:

  speakermeet.ui:
    container_name: speakermeet.ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    tty: true
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
