apiVersion: apps/v1
kind: Deployment
metadata:
  name: speakermeet-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speakermeet-ui
  template:
    metadata:
      labels:
        app: speakermeet-ui
        version: image_label
    spec:
      containers:
      - name: speakermeet-ui
        image: acr_url/speakermeet-ui:image_label
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: speakermeet-ui
spec:
  type: NodePort
  selector:
    app: speakermeet-ui
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: speakermeet-ui
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  # https://docs.microsoft.com/en-us/azure/aks/http-application-routing
  - host: speakermeet-ui.AKS_URL
    http:
      paths:
      - path: /api
        backend:
          serviceName: speakermeet-api
          servicePort: 5000
      - path: /
        backend:
          serviceName: speakermeet-ui
          servicePort: 80
